name: your_project_name
description: A new Flutter project.
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  supabase_flutter: ^2.0.0
  fl_chart: ^0.65.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^12.0.0
  shared_preferences: ^2.2.2
dev_dependencies:
  build_runner:
  freezed:
  json_serializable: